#!/usr/bin/env bash

#Bash script that pings an IP address passed as an argument.
if [ $# -ne 1 ]; then # Check if an argument is provided
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

ip_address=$1 # Extract the IP address from the argument

ping -c 5 $ip_address # Ping the IP address 5 times